travis:
  secure:
    BINSTAR_TOKEN: IWf7A3DQD8I6c+yn0MHAb9PYwEmPRn2tymSJ9vUjKBwmXhzMK5lmNhAmdyWAJ3maSVP/KdNDqRhOUnQ2htas4niVea7/rcge4548+IZYkumhbNVEK7zBbhyOMiEsXqeJddfVUIw+nFbL4IX/sFI45jWvq+oSsyy8veMIKdqiC3QdX4YRMuzjSjXJynbpaESUwZz5QZKdyMKSsngegCPGGKcp+DOhlWS0o1j2zwygkP8KnPAoNkTXfKWx6ZhsP+CjZhODZGMLQroK4PyEoNkbJ59SS6RqM4PJ5hFY4i0aP7NTC70QpPjd9tGY8iWAfF2cclLjW8I693/GgmVq8hmBsy5gqCPP4cso+MXzPw0YJ/oAcZEuHTor0cTwUHrW3phyByYcHE7NNj4xP2prZ77SzeQQJI8WJQ2hQHqEWWKjGWjCax31NxoypzzcajmRoyfL4xv5IW808hGkG1lInNb3Rl6Lvxvxp05fUQnBmoVerTtTjLV9szDB1CNiHBG5QTcBPsbaEO5rx9yMp8B82Pezm99YWapBM+KrD3MHo1M8k85uvV6/dT4gZ80kF0coT7YJy0ExXo+DuiniGH2Yg8k3n/Ap0aFDTa7ip3XqNRV2dp5rT9E8J5OKSwn6nLvLyjSLTX69b/mJ1Lk7wWmhTYuFe4rJjjAXX2+jN2uOmbv4eKU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
